version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"  # Mappe l'API sur le port 8000
    networks:
      - monitoring_network
    volumes:
      - ./models:/app/models  # Monte le dossier des modèles
      - ./data:/app/data      # Monte le dossier des données
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  # Expose l'interface Prometheus
    networks:
      - monitoring_network
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"  # Expose Grafana
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge
