global:
  scrape_interval: 15s  # Intervalle de collecte des métriques

scrape_configs:
  - job_name: "api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:8000"]  # Utilisez le nom du service défini dans docker-compose.yml
